In [1]:
import pandas as pd

In [2]:
weather_df = pd.read_csv('../Data/WeatherEvents_Jan2016-Dec2021.csv')

In [3]:
weather_df.head()

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode
0,W-1,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
1,W-2,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
2,W-3,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,0.03,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
3,W-4,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
4,W-5,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0

In [4]:
weather_df['Type'].value_counts()

Rain             4397546
Fog              1722738
Snow              980411
Cold              197691
Precipitation     128836
Storm              49203
Hail                2740
Name: Type, dtype: int64

In [5]:
weather_df['EventId'].value_counts()

W-1          1
W-5051181    1
W-5051179    1
W-5051178    1
W-5051177    1
            ..
W-2525505    1
W-2525504    1
W-2525503    1
W-2525502    1
W-7577197    1
Name: EventId, Length: 7479165, dtype: int64

In [6]:
weather_df.drop(columns = ['EventId'], inplace =True)

In [7]:
weather_df.head()

,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode
0,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
1,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
2,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,0.03,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
3,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0
4,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0

In [8]:
weather_df.isna().sum()

Type                     0
Severity                 0
StartTime(UTC)           0
EndTime(UTC)             0
Precipitation(in)        0
TimeZone                 0
AirportCode              0
LocationLat              0
LocationLng              0
City                 14563
County                   0
State                    0
ZipCode              59234
dtype: int64

In [9]:
weather_df['Year'] = weather_df['StartTime(UTC)'].str.split('-', expand = True)[0]

In [10]:
weather_df['Month'] = weather_df['StartTime(UTC)'].str.split('-', expand = True)[1]

In [11]:
weather_df['Day'] = weather_df['StartTime(UTC)'].str.split('-', expand = True)[2]

In [12]:
weather_df.head()

,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode,Year,Month,Day
0,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01,06 23:14:00
1,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01,07 04:14:00
2,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,0.03,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01,07 05:54:00
3,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01,08 05:34:00
4,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01,08 13:54:00

In [13]:
weather_df['Day'] = weather_df['Day'].str.split(' ', expand = True)[0]

In [14]:
weather_df.head()

,Type,Severity,StartTime(UTC),EndTime(UTC),Precipitation(in),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode,Year,Month,Day
0,Snow,Light,2016-01-06 23:14:00,2016-01-07 00:34:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01,06
1,Snow,Light,2016-01-07 04:14:00,2016-01-07 04:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01,07
2,Snow,Light,2016-01-07 05:54:00,2016-01-07 15:34:00,0.03,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01,07
3,Snow,Light,2016-01-08 05:34:00,2016-01-08 05:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01,08
4,Snow,Light,2016-01-08 13:54:00,2016-01-08 15:54:00,0.00,US/Mountain,K04V,38.0972,-106.1689,Saguache,Saguache,CO,81149.0,2016,01,08

In [15]:
weather_df.drop(columns = ['StartTime(UTC)','EndTime(UTC)'], inplace =True)

In [16]:
weather_df.drop(columns = ['TimeZone','AirportCode'], inplace =True)

In [17]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7479165 entries, 0 to 7479164
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   Type               object
 1   Severity           object
 2   Precipitation(in)  float64
 3   LocationLat        float64
 4   LocationLng        float64
 5   City               object
 6   County             object
 7   State              object
 8   ZipCode            float64
 9   Year               object
 10  Month              object
 11  Day                object
dtypes: float64(4), object(8)
memory usage: 684.7+ MB

In [18]:
weather_df.drop(columns = ['City','ZipCode'], inplace =True)

In [19]:
weather_df.head()

,Type,Severity,Precipitation(in),LocationLat,LocationLng,County,State,Year,Month,Day
0,Snow,Light,0.00,38.0972,-106.1689,Saguache,CO,2016,01,06
1,Snow,Light,0.00,38.0972,-106.1689,Saguache,CO,2016,01,07
2,Snow,Light,0.03,38.0972,-106.1689,Saguache,CO,2016,01,07
3,Snow,Light,0.00,38.0972,-106.1689,Saguache,CO,2016,01,08
4,Snow,Light,0.00,38.0972,-106.1689,Saguache,CO,2016,01,08

In [20]:
weather_df['State'].value_counts()

TX    516199
MN    383750
MI    358578
FL    325703
NC    317292
CA    309425
WI    272537
GA    250453
IL    243412
VA    231925
IA    211031
LA    194485
WA    191272
OH    183926
NY    182789
SC    182235
PA    180072
AL    172138
CO    169836
WY    161687
OK    157282
OR    152965
AR    137131
ND    136052
IN    133701
NE    126682
MS    125043
MO    117692
KY    115939
MA    107782
KS    103896
MT     90577
WV     88522
ID     85844
SD     80623
ME     79042
NM     72731
TN     70098
NJ     69072
MD     68114
NH     65524
AZ     56071
VT     50141
CT     41850
UT     39952
NV     31310
RI     22399
DE     14385
Name: State, dtype: int64

In [22]:
weather_df.head()

,Type,Severity,Precipitation(in),LocationLat,LocationLng,County,State,Year,Month,Day
0,Snow,Light,0.00,38.0972,-106.1689,Saguache,CO,2016,01,06
1,Snow,Light,0.00,38.0972,-106.1689,Saguache,CO,2016,01,07
2,Snow,Light,0.03,38.0972,-106.1689,Saguache,CO,2016,01,07
3,Snow,Light,0.00,38.0972,-106.1689,Saguache,CO,2016,01,08
4,Snow,Light,0.00,38.0972,-106.1689,Saguache,CO,2016,01,08

In [23]:
weather_df.to_csv('../Data/weather_cleaned.csv')